In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC


In [2]:
data = pd.read_csv('final_with_covid_AS.csv')
data.head()

CountCases  BedDys  BeddystoCC  Severity  DiedCases  DiedBdDys  Hsptlsns  \
0          17     133    7.823529        75          4          9        13   
1          13     372   28.615385        63          4         34         9   
2           8     106   13.250000        48          4         13         4   
3          45     218    4.844444       153          3         24        42   
4          24     238    9.916667        90          3          8        21   

   April  August  December  ...  Y2013  Y2014  Y2015  Y2016  Y2017  Y2018  \
0      0       0         0  ...      1      0      0      0      0      0   
1      0       0         0  ...      0      0      0      0      0      0   
2      0       0         0  ...      0      0      0      0      0      1   
3      0       0         0  ...      0      0      0      1      0      0   
4      0       1         0  ...      1      0      0      0      0      0   

   Y2019  Y2020  Y2021  CovidPrd  
0      0      0      0         0  
1      0      0      0         0  
2      0      0      0         0  
3      0      0      0         0  
4      0      0      0         0  

[5 rows x 58 columns]

In [3]:
data['Severity'] = np.log(data['Severity'])


In [4]:
filtered_data = data

In [5]:
num_bins = 2

bed_days_min = filtered_data['Severity'].min()
bed_days_max = filtered_data['Severity'].max()

bin_width = (bed_days_max - bed_days_min) / num_bins
bins = [bed_days_min + i * bin_width for i in range(num_bins + 1)]

def bin_function(x):
    for i in range(1, len(bins)):
        if x <= bins[i]:
            return i - 1
    return i

filtered_data['Bed_days_category'] = filtered_data['Severity'].apply(bin_function)

In [6]:
filtered_data['Bed_days_category'].value_counts()

0    44186
1     9852
Name: Bed_days_category, dtype: int64

In [7]:
from xgboost import XGBClassifier

X = filtered_data[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021','BedDys',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)


# ارزیابی مدل
y_pred_xgb = xgb_model.predict(X_test)
acc_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)

precision_xgb = precision_score(y_test, y_pred_xgb) 
recall_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)

print('Accuracy:', acc_xgb)
print('Confusion Matrix:\n', conf_matrix_xgb)
print('Classification Report:\n', class_report_xgb)
print('Precision:', precision_xgb)
print('Recall:', recall_xgb)
print('F1-score:', f1_xgb)

Accuracy: 0.9085245497162595
Confusion Matrix:
 [[12450   745]
 [  738  2279]]
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.94      0.94     13195
           1       0.75      0.76      0.75      3017

    accuracy                           0.91     16212
   macro avg       0.85      0.85      0.85     16212
weighted avg       0.91      0.91      0.91     16212

Precision: 0.7536375661375662
Recall: 0.7553861451773285
F1-score: 0.7545108425757325


In [8]:
from xgboost import XGBClassifier

X = filtered_data[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012','BedDys',
                   'CovidPrd']]



y = filtered_data['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.7536375661375662
0.7553861451773285
0.7545108425757325
[[12450   745]
 [  738  2279]]
0    44186
1     9852
Name: Bed_days_category, dtype: int64
0.9085245497162595


In [9]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.3535353535353536
مقدار F1 Score بهترین آستانه: 0.7715478675812705


In [10]:
y_test.value_counts()

0    13195
1     3017
Name: Bed_days_category, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from imblearn.over_sampling import RandomOverSampler

# پیش از تقسیم داده‌ها به آموزش و آزمون
ros = RandomOverSampler(random_state=42,sampling_strategy='not majority')
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# سپس ادامه کد با داده‌های جدید
#X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.3, random_state=42)

# مدل‌های پایه
base_models = [
     XGBClassifier(objective='binary:logistic', random_state=42),
    RandomForestClassifier(random_state=42),
    DecisionTreeClassifier(random_state=42),
    GradientBoostingClassifier(random_state=42),
    KNeighborsClassifier(n_neighbors=5),
    SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42),
    GaussianNB(),
    ExtraTreesClassifier(random_state=42),
    MLPClassifier(hidden_layer_sizes=(64,), random_state=42),
]

# آموزش مدل‌های پایه
for model in base_models:
    model.fit(X_train, y_train)

# ایجاد ویژگی‌های جدید از خروجی مدل‌های پایه
X_train_meta = [model.predict_proba(X_train) for model in base_models]
X_train_meta = np.concatenate(X_train_meta, axis=1)

X_test_meta = [model.predict_proba(X_test) for model in base_models]
X_test_meta = np.concatenate(X_test_meta, axis=1)

# ایجاد و آموزش مدل متا-طبقه‌بند
meta_model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))
meta_model.fit(X_train_meta, y_train)

# ارزیابی مدل
y_pred = meta_model.predict(X_test_meta)
acc = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
from sklearn.metrics import classification_report

# ارزیابی مدل
y_pred = meta_model.predict(X_test_meta)
class_report = classification_report(y_test, y_pred)

print(class_report)
print('Accuracy:', acc)
print('Confusion Matrix:\n', conf_matrix)

In [11]:
from sklearn.linear_model import LogisticRegression

# Assuming X and y are already defined as in your code snippet

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the logistic regression model
log_reg_model = LogisticRegression(random_state=42)

# Fit the model to the training data
log_reg_model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_log_reg = log_reg_model.predict(X_test)

# Calculate evaluation metrics
accuracy_log_reg = accuracy_score(y_test, y_pred_log_reg)
conf_matrix_log_reg = confusion_matrix(y_test, y_pred_log_reg)
class_report_log_reg = classification_report(y_test, y_pred_log_reg)
precision_log_reg = precision_score(y_test, y_pred_log_reg)
recall_log_reg = recall_score(y_test, y_pred_log_reg)
f1_log_reg = f1_score(y_test, y_pred_log_reg)

# Print the evaluation metrics
print("Precision:", precision_log_reg)
print("Recall:", recall_log_reg)
print("F1 Score:", f1_log_reg)
print("Confusion Matrix:\n", confusion_matrix(y_true=y_test, y_pred=y_pred_log_reg))
print("Class Distribution:\n", y.value_counts())
print("Accuracy:", accuracy_log_reg)


Precision: 0.7831598008148484
Recall: 0.573417301955585
F1 Score: 0.6620742441637965
Confusion Matrix:
 [[12716   479]
 [ 1287  1730]]
Class Distribution:
 0    44186
1     9852
Name: Bed_days_category, dtype: int64
Accuracy: 0.8910683444362201


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
from sklearn.svm import SVC

# Assuming X and y are already defined as in your code snippet

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the SVM model
svm_model = SVC(random_state=42)

# Fit the model to the training data
svm_model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_svm = svm_model.predict(X_test)

# Calculate evaluation metrics
accuracy_svm = accuracy_score(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
class_report_svm = classification_report(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm)
recall_svm = recall_score(y_test, y_pred_svm)
f1_svm = f1_score(y_test, y_pred_svm)

# Print the evaluation metrics
print("Precision:", precision_svm)
print("Recall:", recall_svm)
print("F1 Score:", f1_svm)
print("Confusion Matrix:\n", confusion_matrix(y_true=y_test, y_pred=y_pred_svm))
print("Class Distribution:\n", y.value_counts())
print("Accuracy:", accuracy_svm)


Precision: 0.729175565997437
Recall: 0.5657938349353663
F1 Score: 0.6371780515117581
Confusion Matrix:
 [[12561   634]
 [ 1310  1707]]
Class Distribution:
 0    44186
1     9852
Name: Bed_days_category, dtype: int64
Accuracy: 0.8800888230940045


In [13]:
from sklearn.ensemble import RandomForestClassifier

# Assuming X and y are already defined as in your code snippet

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Random Forest model
rf_model = RandomForestClassifier(random_state=42)

# Fit the model to the training data
rf_model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_rf = rf_model.predict(X_test)

# Calculate evaluation metrics
accuracy_rf = accuracy_score(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
class_report_rf = classification_report(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

# Print the evaluation metrics
print("Precision:", precision_rf)
print("Recall:", recall_rf)
print("F1 Score:", f1_rf)
print("Confusion Matrix:\n", confusion_matrix(y_true=y_test, y_pred=y_pred_rf))
print("Class Distribution:\n", y.value_counts())
print("Accuracy:", accuracy_rf)


Precision: 0.7512280701754386
Recall: 0.7096453430560159
F1 Score: 0.7298448951764104
Confusion Matrix:
 [[12486   709]
 [  876  2141]]
Class Distribution:
 0    44186
1     9852
Name: Bed_days_category, dtype: int64
Accuracy: 0.902232913890945


In [14]:
from sklearn.neural_network import MLPClassifier

# Assuming X and y are already defined as in your code snippet

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the MLP classifier
mlp_model = MLPClassifier(random_state=42)

# Fit the model to the training data
mlp_model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_mlp = mlp_model.predict(X_test)

# Calculate evaluation metrics
accuracy_mlp = accuracy_score(y_test, y_pred_mlp)
conf_matrix_mlp = confusion_matrix(y_test, y_pred_mlp)
class_report_mlp = classification_report(y_test, y_pred_mlp)
precision_mlp = precision_score(y_test, y_pred_mlp)
recall_mlp = recall_score(y_test, y_pred_mlp)
f1_mlp = f1_score(y_test, y_pred_mlp)

# Print the evaluation metrics
print("Precision:", precision_mlp)
print("Recall:", recall_mlp)
print("F1 Score:", f1_mlp)
print("Confusion Matrix:\n", confusion_matrix(y_true=y_test, y_pred=y_pred_mlp))
print("Class Distribution:\n", y.value_counts())
print("Accuracy:", accuracy_mlp)


Precision: 0.7454364420843014
Recall: 0.7444481272787538
F1 Score: 0.7449419568822554
Confusion Matrix:
 [[12428   767]
 [  771  2246]]
Class Distribution:
 0    44186
1     9852
Name: Bed_days_category, dtype: int64
Accuracy: 0.9051320009869233


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
