In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from xgboost import XGBClassifier

import xgboost as xgb

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from imblearn.over_sampling import RandomOverSampler


In [18]:
data = pd.read_csv('final_with_covid_AS.csv')
data.head()

CountCases  BedDys  BeddystoCC  Severity  DiedCases  DiedBdDys  Hsptlsns  \
0          17     133    7.823529        75          4          9        13   
1          13     372   28.615385        63          4         34         9   
2           8     106   13.250000        48          4         13         4   
3          45     218    4.844444       153          3         24        42   
4          24     238    9.916667        90          3          8        21   

   April  August  December  ...  Y2013  Y2014  Y2015  Y2016  Y2017  Y2018  \
0      0       0         0  ...      1      0      0      0      0      0   
1      0       0         0  ...      0      0      0      0      0      0   
2      0       0         0  ...      0      0      0      0      0      1   
3      0       0         0  ...      0      0      0      1      0      0   
4      0       1         0  ...      1      0      0      0      0      0   

   Y2019  Y2020  Y2021  CovidPrd  
0      0      0      0         0  
1      0      0      0         0  
2      0      0      0         0  
3      0      0      0         0  
4      0      0      0         0  

[5 rows x 58 columns]

In [58]:
data.head()

CountCases  BedDys  BeddystoCC  Severity  DiedCases  DiedBdDys  Hsptlsns  \
0          17     133    2.057136        75          4          9        13   
1          13     372    3.353944        63          4         34         9   
2           8     106    2.583998        48          4         13         4   
3          45     218    1.577833       153          3         24        42   
4          24     238    2.294217        90          3          8        21   

   April  August  December  ...  Y2013  Y2014  Y2015  Y2016  Y2017  Y2018  \
0      0       0         0  ...      1      0      0      0      0      0   
1      0       0         0  ...      0      0      0      0      0      0   
2      0       0         0  ...      0      0      0      0      0      1   
3      0       0         0  ...      0      0      0      1      0      0   
4      0       1         0  ...      1      0      0      0      0      0   

   Y2019  Y2020  Y2021  CovidPrd  
0      0      0      0         0  
1      0      0      0         0  
2      0      0      0         0  
3      0      0      0         0  
4      0      0      0         0  

[5 rows x 58 columns]

In [19]:
filtered_data = data[data['CarDriver'] == 1]
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12582 entries, 11 to 54025
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CountCases       12582 non-null  int64  
 1   BedDys           12582 non-null  int64  
 2   BeddystoCC       12582 non-null  float64
 3   Severity         12582 non-null  int64  
 4   DiedCases        12582 non-null  int64  
 5   DiedBdDys        12582 non-null  int64  
 6   Hsptlsns         12582 non-null  int64  
 7   April            12582 non-null  int64  
 8   August           12582 non-null  int64  
 9   December         12582 non-null  int64  
 10  February         12582 non-null  int64  
 11  January          12582 non-null  int64  
 12  July             12582 non-null  int64  
 13  June             12582 non-null  int64  
 14  March            12582 non-null  int64  
 15  May              12582 non-null  int64  
 16  November         12582 non-null  int64  
 17  October    

In [20]:
data['BeddystoCC'] = np.log(data['BeddystoCC'])


In [21]:

filtered_data['Bed_days_category'] = np.where(filtered_data['BeddystoCC'] >=7, 1, 0)

filtered_data['Bed_days_category'].value_counts()


/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1820/3156086116.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Bed_days_category'] = np.where(filtered_data['BeddystoCC'] >=7, 1, 0)


0    9688
1    2894
Name: Bed_days_category, dtype: int64

In [5]:
data['BeddystoCC'].describe()

count    54038.000000
mean         5.559310
std         10.839189
min          1.000000
25%          1.000000
50%          2.500000
75%          5.875000
max        608.000000
Name: BeddystoCC, dtype: float64

In [6]:

from xgboost import XGBClassifier

X = filtered_data[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)



0.534020618556701
0.29265536723163843
0.3781021897810219
[[2664  226]
 [ 626  259]]
0    9688
1    2894
Name: Bed_days_category, dtype: int64
0.7743046357615894


In [7]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)


بهترین آستانه با توجه به F1 Score: 0.20202020202020204
مقدار F1 Score بهترین آستانه: 0.49518459069020876


In [8]:
from imblearn.over_sampling import SMOTE, ADASYN
from imblearn.combine import SMOTEENN, SMOTETomek
from sklearn.datasets import make_classification


oversampler = SMOTE(random_state=42)
X_smote, y_smote = oversampler.fit_resample(X_train, y_train)

oversampler = ADASYN(random_state=42)
X_adasyn, y_adasyn = oversampler.fit_resample(X_smote, y_smote)






# روش دوم: ترکیب SMOTE با ENN یا Tomek links
oversampler = SMOTEENN(random_state=42)
X_smoteenn, y_smoteenn = oversampler.fit_resample(X_adasyn, y_adasyn)

oversampler = SMOTETomek(random_state=42)
X_smotetomek, y_smotetomek = oversampler.fit_resample(X_smoteenn, y_smoteenn)

# نمایش نتایج
print("تعداد نمونه های اولیه:", len(y))
print("تعداد نمونه های SMOTE + ADASYN:", len(y_adasyn))
print("تعداد نمونه های SMOTEENN:", len(y_smoteenn))
print("تعداد نمونه های SMOTETomek:", len(y_smotetomek))
X_smotetomek.shape

تعداد نمونه های اولیه: 12582
تعداد نمونه های SMOTE + ADASYN: 13596
تعداد نمونه های SMOTEENN: 6665
تعداد نمونه های SMOTETomek: 9138


(9138, 39)

In [9]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

# تولید داده‌ مصنوعی بر اساس ترکیبی از oversampling و undersampling

    # ایجاد یک نمونه یادگیری

    # تقسیم داده‌ها به تمرین و تست
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # oversampling با استفاده از SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X, y)

    # undersampling با استفاده از RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = rus.fit_resample(X_train_resampled, y_train_resampled)


# استفاده از توابع

X_train_resampled.shape
# حالا می‌توانید داده‌های متوازنه را به یادگیری مدل می‌دهید

(19376, 39)

In [10]:

from xgboost import XGBClassifier

X = filtered_data[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train_resampled, y_train_resampled)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)



0.5308310991957105
0.6711864406779661
0.592814371257485
[[2365  525]
 [ 291  594]]
0    9688
1    2894
Name: Bed_days_category, dtype: int64
0.783841059602649


In [11]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)


بهترین آستانه با توجه به F1 Score: 0.42424242424242425
مقدار F1 Score بهترین آستانه: 0.6093126385809312


In [12]:
print(classification_report(y_test, y_pred_xgb))


              precision    recall  f1-score   support

           0       0.89      0.82      0.85      2890
           1       0.53      0.67      0.59       885

    accuracy                           0.78      3775
   macro avg       0.71      0.74      0.72      3775
weighted avg       0.81      0.78      0.79      3775



In [13]:

# پیش از تقسیم داده‌ها به آموزش و آزمون
ros = RandomOverSampler(random_state=42)
#X_resampled, y_resampled = ros.fit_resample(X, y)

# سپس ادامه کد با داده‌های جدید
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
# 
base_models = [
     XGBClassifier(objective='binary:logistic', random_state=42),
     #RandomForestClassifier(random_state=42),
     #DecisionTreeClassifier(random_state=42),
     #GradientBoostingClassifier(random_state=42),
     #KNeighborsClassifier(n_neighbors=5),
     #SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42),
     #GaussianNB(),
    # ExtraTreesClassifier(random_state=42),
     MLPClassifier(hidden_layer_sizes=(64,), random_state=42),
]

# آموزش مدل‌های پایه
for model in base_models:
    model.fit(X_train_resampled, y_train_resampled)

# ایجاد ویژگی‌های جدید از خروجی مدل‌های پایه
X_train_meta = [model.predict_proba(X_train_resampled) for model in base_models]
X_train_meta = np.concatenate(X_train_meta, axis=1)

X_test_meta = [model.predict_proba(X_test) for model in base_models]
X_test_meta = np.concatenate(X_test_meta, axis=1)

# ایجاد و آموزش مدل متا-طبقه‌بند
meta_model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))
meta_model.fit(X_train_meta, y_train_resampled)

# ارزیابی مدل
y_pred = meta_model.predict(X_test_meta)
acc = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
from sklearn.metrics import classification_report

# ارزیابی مدل
y_pred = meta_model.predict(X_test_meta)
class_report = classification_report(y_test, y_pred)
f1= f1_score(y_test,y_pred)

print(class_report)
print('Accuracy:', acc)
print('Confusion Matrix:\n', conf_matrix)
print(f1)

              precision    recall  f1-score   support

           0       0.89      0.84      0.86      2890
           1       0.55      0.65      0.59       885

    accuracy                           0.79      3775
   macro avg       0.72      0.74      0.73      3775
weighted avg       0.81      0.79      0.80      3775

Accuracy: 0.791523178807947
Confusion Matrix:
 [[2416  474]
 [ 313  572]]
0.5924391506991197


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# car passanger


In [22]:
filtered_data2 = data[data['CarPngr'] == 1]

In [45]:
data['BeddystoCC'] = np.log(data['BeddystoCC'])


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arraylike.py:397: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [23]:
filtered_data2['Bed_days_category'] = np.where(filtered_data2['BeddystoCC'] >= 1, 1, 0)

filtered_data2['Bed_days_category'].value_counts()

/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1820/727072877.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data2['Bed_days_category'] = np.where(filtered_data2['BeddystoCC'] >= 1, 1, 0)


0    6509
1    5280
Name: Bed_days_category, dtype: int64

In [26]:
from xgboost import XGBClassifier

X = filtered_data2[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data2['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.5945548197203826
0.49661954517516904
0.5411922304085733
[[1359  551]
 [ 819  808]]
0    6509
1    5280
Name: Bed_days_category, dtype: int64
0.6126661012157195


In [27]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.24242424242424243
مقدار F1 Score بهترین آستانه: 0.6470858191831115


In [28]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

# تولید داده‌ مصنوعی بر اساس ترکیبی از oversampling و undersampling

    # ایجاد یک نمونه یادگیری

    # تقسیم داده‌ها به تمرین و تست
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # oversampling با استفاده از SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X, y)

    # undersampling با استفاده از RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = rus.fit_resample(X_train_resampled, y_train_resampled)


# استفاده از توابع

X_train_resampled.shape
# حالا می‌توانید داده‌های متوازنه را به یادگیری مدل می‌دهید

(13018, 39)

In [29]:
from xgboost import XGBClassifier

X = filtered_data2[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data2['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train_resampled, y_train_resampled)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.7073170731707317
0.7129686539643516
0.7101316192225283
[[1430  480]
 [ 467 1160]]
0    6509
1    5280
Name: Bed_days_category, dtype: int64
0.7322589765337857


In [30]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.4545454545454546
مقدار F1 Score بهترین آستانه: 0.7228090208392808


# Mtrcyclist

In [32]:

filtered_data3 = data[data['Mtrcyclist'] == 1]
filtered_data3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11227 entries, 3 to 54034
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CountCases       11227 non-null  int64  
 1   BedDys           11227 non-null  int64  
 2   BeddystoCC       11227 non-null  float64
 3   Severity         11227 non-null  int64  
 4   DiedCases        11227 non-null  int64  
 5   DiedBdDys        11227 non-null  int64  
 6   Hsptlsns         11227 non-null  int64  
 7   April            11227 non-null  int64  
 8   August           11227 non-null  int64  
 9   December         11227 non-null  int64  
 10  February         11227 non-null  int64  
 11  January          11227 non-null  int64  
 12  July             11227 non-null  int64  
 13  June             11227 non-null  int64  
 14  March            11227 non-null  int64  
 15  May              11227 non-null  int64  
 16  November         11227 non-null  int64  
 17  October     

In [33]:

filtered_data3['Bed_days_category'] = np.where(filtered_data3['BeddystoCC'] >= 1.5, 1, 0)

filtered_data3['Bed_days_category'].value_counts()

/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1820/3051034273.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data3['Bed_days_category'] = np.where(filtered_data3['BeddystoCC'] >= 1.5, 1, 0)


0    6977
1    4250
Name: Bed_days_category, dtype: int64

In [34]:
from xgboost import XGBClassifier

X = filtered_data3[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data3['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.6278195488721805
0.5231010180109632
0.5706962836394703
[[1696  396]
 [ 609  668]]
0    6977
1    4250
Name: Bed_days_category, dtype: int64
0.7016918967052538


In [35]:

# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.24242424242424243
مقدار F1 Score بهترین آستانه: 0.6261453879047036


In [36]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

# تولید داده‌ مصنوعی بر اساس ترکیبی از oversampling و undersampling

    # ایجاد یک نمونه یادگیری

    # تقسیم داده‌ها به تمرین و تست
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # oversampling با استفاده از SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X, y)

    # undersampling با استفاده از RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = rus.fit_resample(X_train_resampled, y_train_resampled)


# استفاده از توابع

X_train_resampled.shape
# 

(13954, 39)

In [37]:
from xgboost import XGBClassifier

X = filtered_data3[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data3['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train_resampled, y_train_resampled)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.6919228020014296
0.7580266249021144
0.7234678624813156
[[1661  431]
 [ 309  968]]
0    6977
1    4250
Name: Bed_days_category, dtype: int64
0.7803502523003859


In [38]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.4444444444444445
مقدار F1 Score بهترین آستانه: 0.7286767286767287


# PdlCyclist

In [39]:
filtered_data4 = data[data['PdlCyclist'] == 1]
filtered_data4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12354 entries, 32 to 54035
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CountCases       12354 non-null  int64  
 1   BedDys           12354 non-null  int64  
 2   BeddystoCC       12354 non-null  float64
 3   Severity         12354 non-null  int64  
 4   DiedCases        12354 non-null  int64  
 5   DiedBdDys        12354 non-null  int64  
 6   Hsptlsns         12354 non-null  int64  
 7   April            12354 non-null  int64  
 8   August           12354 non-null  int64  
 9   December         12354 non-null  int64  
 10  February         12354 non-null  int64  
 11  January          12354 non-null  int64  
 12  July             12354 non-null  int64  
 13  June             12354 non-null  int64  
 14  March            12354 non-null  int64  
 15  May              12354 non-null  int64  
 16  November         12354 non-null  int64  
 17  October    

In [44]:

filtered_data4['Bed_days_category'] = np.where(filtered_data4['BeddystoCC'] >= 1, 1, 0)
filtered_data4['Bed_days_category'].value_counts()

/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1820/2659493898.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data4['Bed_days_category'] = np.where(filtered_data4['BeddystoCC'] >= 1, 1, 0)


0    8618
1    3736
Name: Bed_days_category, dtype: int64

In [45]:
from xgboost import XGBClassifier

X = filtered_data4[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data4['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.5264367816091954
0.4221198156682028
0.4685421994884911
[[2210  412]
 [ 627  458]]
0    8618
1    3736
Name: Bed_days_category, dtype: int64
0.7197194496897761


In [46]:

# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.22222222222222224
مقدار F1 Score بهترین آستانه: 0.5556295802798135


In [47]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

# تولید داده‌ مصنوعی بر اساس ترکیبی از oversampling و undersampling

    # ایجاد یک نمونه یادگیری

    # تقسیم داده‌ها به تمرین و تست
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # oversampling با استفاده از SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X, y)

    # undersampling با استفاده از RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = rus.fit_resample(X_train_resampled, y_train_resampled)


# استفاده از توابع

X_train_resampled.shape

(17236, 39)

In [48]:
from xgboost import XGBClassifier

X = filtered_data4[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data4['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train_resampled, y_train_resampled)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.5980611483967189
0.7391705069124423
0.6611706512778236
[[2083  539]
 [ 283  802]]
0    8618
1    3736
Name: Bed_days_category, dtype: int64
0.7782573509576477


In [49]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.4444444444444445
مقدار F1 Score بهترین آستانه: 0.6717674062739097


# Pedestrian

In [50]:
filtered_data5 = data[data['Pedestrian'] == 1]
filtered_data5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6086 entries, 0 to 54037
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CountCases       6086 non-null   int64  
 1   BedDys           6086 non-null   int64  
 2   BeddystoCC       6086 non-null   float64
 3   Severity         6086 non-null   int64  
 4   DiedCases        6086 non-null   int64  
 5   DiedBdDys        6086 non-null   int64  
 6   Hsptlsns         6086 non-null   int64  
 7   April            6086 non-null   int64  
 8   August           6086 non-null   int64  
 9   December         6086 non-null   int64  
 10  February         6086 non-null   int64  
 11  January          6086 non-null   int64  
 12  July             6086 non-null   int64  
 13  June             6086 non-null   int64  
 14  March            6086 non-null   int64  
 15  May              6086 non-null   int64  
 16  November         6086 non-null   int64  
 17  October      

In [51]:

filtered_data5['Bed_days_category'] = np.where(filtered_data5['BeddystoCC'] >= 1.5, 1, 0)
filtered_data5['Bed_days_category'].value_counts()

/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1820/3345489342.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data5['Bed_days_category'] = np.where(filtered_data5['BeddystoCC'] >= 1.5, 1, 0)


0    3251
1    2835
Name: Bed_days_category, dtype: int64

In [52]:
from xgboost import XGBClassifier

X = filtered_data5[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data5['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.6549210206561361
0.6267441860465116
0.6405228758169935
[[682 284]
 [321 539]]
0    3251
1    2835
Name: Bed_days_category, dtype: int64
0.6686746987951807


In [53]:

# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.29292929292929293
مقدار F1 Score بهترین آستانه: 0.6795740561471443


In [54]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

# تولید داده‌ مصنوعی بر اساس ترکیبی از oversampling و undersampling

    # ایجاد یک نمونه یادگیری

    # تقسیم داده‌ها به تمرین و تست
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # oversampling با استفاده از SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X, y)

    # undersampling با استفاده از RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = rus.fit_resample(X_train_resampled, y_train_resampled)


# استفاده از توابع

X_train_resampled.shape

(6502, 39)

In [56]:
from xgboost import XGBClassifier

X = filtered_data5[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data5['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train_resampled, y_train_resampled)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb= recall_score(y_test, y_pred_xgb)
f1_xgb= f1_score(y_test,y_pred_xgb)
print(precision_xgb)
print(recall_xgb)
print(f1_xgb)
print(confusion_matrix(y_true=y_test,y_pred=y_pred_xgb))
print(y.value_counts())
print(accuracy_xgb)

0.7912341407151096
0.7976744186046512
0.7944412275622466
[[785 181]
 [174 686]]
0    3251
1    2835
Name: Bed_days_category, dtype: int64
0.8055859802847755


In [57]:
# برای محاسبه احتمالات پیش‌بینی هر کلاس
y_pred_proba_svm = xgb_model.predict_proba(X_test)
# در اینجا y_pred_proba_svm یک آرایه با ابعاد (تعداد نمونه‌ها، تعداد کلاس‌ها) است

# حالا برای هر آستانه ممکن احتمالات را به پیش‌بینی تبدیل می‌کنیم
thresholds = np.linspace(0, 1, 100)
f1_scores = []
for threshold in thresholds:
    y_pred_threshold = (y_pred_proba_svm[:, 1] >= threshold).astype(int)
    f1_scores.append(f1_score(y_test, y_pred_threshold))

# بهترین آستانه را با توجه به F1 Score پیدا می‌کنیم
best_threshold_index = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_index]
best_f1_score = f1_scores[best_threshold_index]

print("بهترین آستانه با توجه به F1 Score:", best_threshold)
print("مقدار F1 Score بهترین آستانه:", best_f1_score)

بهترین آستانه با توجه به F1 Score: 0.4646464646464647
مقدار F1 Score بهترین آستانه: 0.802019068984857
