In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix

/Users/amin/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
data = pd.read_excel("National_Accidents_Australia.xlsx")

In [3]:
label_encoder = LabelEncoder()
data['Month'] = label_encoder.fit_transform(data['Month'])
data['ABS remoteness area'] = label_encoder.fit_transform(data['ABS remoteness area'])
data['Cause of injury'] = label_encoder.fit_transform(data['Cause of injury'])
data['Age group'] = label_encoder.fit_transform(data['Age group'])
data['Sex'] = label_encoder.fit_transform(data['Sex'])
data['Road user'] = label_encoder.fit_transform(data['Road user'])
data['Counterparty'] = label_encoder.fit_transform(data['Counterparty'])



In [4]:
data['Died_cases'].fillna(0, inplace=True)

data['Died_bed_days'].fillna(0, inplace=True)

data.dropna(subset=['Count of cases'], inplace=True)


data.head()

Calendar year  Month  ABS remoteness area  Cause of injury  Age group  Sex  \
0           2011      0                    0                0          0    0   
1           2011      0                    0                0          0    1   
2           2011      0                    0                0          1    0   
3           2011      0                    0                0          1    1   
4           2011      0                    0                0          2    0   

   Road user  Counterparty  Count of cases  Bed days  Died_cases  \
0          8             5           765.0      1007         0.0   
1          8             5          1010.0      1694         0.0   
2          8             5           859.0      1597         0.0   
3          8             5          2231.0      3878         2.0   
4          8             5          1098.0      2347         1.0   

   Died_bed_days  Hospitalisations  
0            0.0               765  
1            0.0              1010  
2            0.0               859  
3            3.0              2229  
4           14.0              1097

In [5]:

label_encoder = LabelEncoder()
data['Month'] = label_encoder.fit_transform(data['Month'])
data['ABS remoteness area'] = label_encoder.fit_transform(data['ABS remoteness area'])
data['Cause of injury'] = label_encoder.fit_transform(data['Cause of injury'])
data['Age group'] = label_encoder.fit_transform(data['Age group'])
data['Sex'] = label_encoder.fit_transform(data['Sex'])
data['Road user'] = label_encoder.fit_transform(data['Road user'])
data['Counterparty'] = label_encoder.fit_transform(data['Counterparty'])


In [15]:
data['Bed_days_category'] = np.where(data['Bed days'] >= 30, 1, 0)
data['Bed_days_category'].value_counts()

0    74918
1    38064
Name: Bed_days_category, dtype: int64

In [32]:
data['Road user'].value_counts()

8     31420
1     16055
2     14876
10    14309
7     13975
11     7378
3      4723
9      2904
12     2339
4      2306
0      1800
5       512
6       385
Name: Road user, dtype: int64

# CLASSIFICATION WITH ROAD USERS 8---> Not applicable

In [90]:
filtered_data = data[data['Road user'] == 8]
filtered_data.head()

Calendar year  Month  ABS remoteness area  Cause of injury  Age group  Sex  \
0           2011      0                    0                0          0    0   
1           2011      0                    0                0          0    1   
2           2011      0                    0                0          1    0   
3           2011      0                    0                0          1    1   
4           2011      0                    0                0          2    0   

   Road user  Counterparty  Count of cases  Bed days  Died_cases  \
0          8             5           765.0      1007         0.0   
1          8             5          1010.0      1694         0.0   
2          8             5           859.0      1597         0.0   
3          8             5          2231.0      3878         2.0   
4          8             5          1098.0      2347         1.0   

   Died_bed_days  Hospitalisations  Bed_days_category  
0            0.0               765                  1  
1            0.0              1010                  1  
2            0.0               859                  1  
3            3.0              2229                  1  
4           14.0              1097                  1

In [91]:
X = filtered_data[['Count of cases', 'Died_cases', 'Hospitalisations']]
y = (filtered_data['Bed days'] > 30).astype(int)  

In [18]:
print(len(X))


31420


In [22]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

xgb_classifier = XGBClassifier(random_state=42)
xgb_classifier.fit(X_train, y_train)

y_predxgb = xgb_classifier.predict(X_test)

precision_xgb6 = precision_score(y_test,y_predxgb)
recall_xgb6= recall_score(y_test, y_predxgb)
f1_xgb6= f1_score(y_test,y_predxgb)
print(precision_xgb6)
print(recall_xgb6)
print(f1_xgb6)
print(confusion_matrix(y_true=y_test,y_pred=y_predxgb))

0.9342915811088296
0.9442848020434227
0.9392616117506947
[[2746  416]
 [ 349 5915]]


# CLASSIFICATION WITH ROAD USERS 1---> Car driver                          


In [52]:
filtered_data2 = data[data['Road user'] == 7]
filtered_data2.head()

Calendar year  Month  ABS remoteness area  Cause of injury  Age group  \
66           2011      0                    0                4          0   
82           2011      0                    0                4          1   
83           2011      0                    0                4          1   
84           2011      0                    0                4          1   
85           2011      0                    0                4          1   

    Sex  Road user  Counterparty  Count of cases  Bed days  Died_cases  \
66    1          7             1             1.0         1         0.0   
82    0          7             0             1.0         1         0.0   
83    0          7             1             4.0         8         0.0   
84    0          7             2             1.0         1         0.0   
85    0          7             4             8.0        33         0.0   

    Died_bed_days  Hospitalisations  Bed_days_category  
66            0.0                 1                  0  
82            0.0                 1                  0  
83            0.0                 4                  0  
84            0.0                 1                  0  
85            0.0                 8                  1

In [53]:
X2 = filtered_data2[['Count of cases', 'Died_cases', 'Hospitalisations']]
y2 = (filtered_data2['Bed days'] > 30).astype(int) 

In [71]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.3)

xgb_classifier2 = XGBClassifier(random_state=42)
xgb_classifier2.fit(X_train2, y_train2)

y_predxgb2 = xgb_classifier2.predict(X_test2)

precision_xgb2 = precision_score(y_test2,y_predxgb2)
recall_xgb2= recall_score(y_test2, y_predxgb2)
f1_xgb2= f1_score(y_test2,y_predxgb2)
print(precision_xgb2)
print(recall_xgb2)
print(f1_xgb2)
print(confusion_matrix(y_true=y_test2,y_pred=y_predxgb2))

0.8754448398576512
0.6362068965517241
0.7368946580129805
[[2928  105]
 [ 422  738]]


# CLASSIFICATION WITH ROAD USERS 2---> Car passenger                          


In [69]:
filtered_data3 = data[data['Road user'] == 2]
filtered_data3.head()

Calendar year  Month  ABS remoteness area  Cause of injury  Age group  \
54           2011      0                    0                4          0   
55           2011      0                    0                4          0   
56           2011      0                    0                4          0   
57           2011      0                    0                4          0   
63           2011      0                    0                4          0   

    Sex  Road user  Counterparty  Count of cases  Bed days  Died_cases  \
54    0          2             1             5.0       214         0.0   
55    0          2             2             2.0        21         0.0   
56    0          2             3             1.0         1         0.0   
57    0          2             4             1.0         1         0.0   
63    1          2             1             4.0         5         0.0   

    Died_bed_days  Hospitalisations  Bed_days_category  
54            0.0                 5                  1  
55            0.0                 2                  0  
56            0.0                 1                  0  
57            0.0                 1                  0  
63            0.0                 4                  0

In [70]:
X3 = filtered_data3[['Count of cases', 'Died_cases', 'Hospitalisations']]
y3 = (filtered_data3['Bed days'] > 30).astype(int) 

In [92]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.3)

xgb_classifier3 = XGBClassifier(random_state=42,scale_pos_weight=4)
xgb_classifier3.fit(X_train3, y_train3)

y_predxgb3 = xgb_classifier3.predict(X_test3)

precision_xgb3 = precision_score(y_test3,y_predxgb3)
recall_xgb3= recall_score(y_test3, y_predxgb3)
f1_xgb3= f1_score(y_test3,y_predxgb3)
print(precision_xgb3)
print(recall_xgb3)
print(f1_xgb3)
print(confusion_matrix(y_true=y_test3,y_pred=y_predxgb3))

0.4355300859598854
0.6350974930362117
0.5167138810198301
[[3154  591]
 [ 262  456]]


# Pedal cyclist

In [94]:
filtered_data4 = data[data['Road user'] == 10]
filtered_data4.head()

Calendar year  Month  ABS remoteness area  Cause of injury  Age group  \
60           2011      0                    0                4          0   
61           2011      0                    0                4          0   
67           2011      0                    0                4          0   
68           2011      0                    0                4          0   
69           2011      0                    0                4          0   

    Sex  Road user  Counterparty  Count of cases  Bed days  Died_cases  \
60    0         10             4             1.0         1         0.0   
61    0         10             6             1.0         2         0.0   
67    1         10             1             1.0         1         0.0   
68    1         10             2             1.0         1         0.0   
69    1         10             4             2.0         2         0.0   

    Died_bed_days  Hospitalisations  Bed_days_category  
60            0.0                 1                  0  
61            0.0                 1                  0  
67            0.0                 1                  0  
68            0.0                 1                  0  
69            0.0                 2                  0

In [95]:
X4 = filtered_data4[['Count of cases', 'Died_cases', 'Hospitalisations']]
y4 = (filtered_data4['Bed days'] > 30).astype(int) 

In [103]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.2)

xgb_classifier4 = XGBClassifier(random_state=42,scale_pos_weight=10)
xgb_classifier4.fit(X_train4, y_train4)

y_predxgb4 = xgb_classifier4.predict(X_test4)

precision_xgb4 = precision_score(y_test4,y_predxgb4)
recall_xgb4= recall_score(y_test4, y_predxgb4)
f1_xgb4= f1_score(y_test4,y_predxgb4)
print(precision_xgb4)
print(recall_xgb4)
print(f1_xgb4)
print(confusion_matrix(y_true=y_test4,y_pred=y_predxgb4))

0.375
0.8463687150837989
0.5197255574614065
[[1999  505]
 [  55  303]]


# Motorcyclist

In [106]:
filtered_data5 = data[data['Road user'] == 7]
filtered_data5.head()

Calendar year  Month  ABS remoteness area  Cause of injury  Age group  \
66           2011      0                    0                4          0   
82           2011      0                    0                4          1   
83           2011      0                    0                4          1   
84           2011      0                    0                4          1   
85           2011      0                    0                4          1   

    Sex  Road user  Counterparty  Count of cases  Bed days  Died_cases  \
66    1          7             1             1.0         1         0.0   
82    0          7             0             1.0         1         0.0   
83    0          7             1             4.0         8         0.0   
84    0          7             2             1.0         1         0.0   
85    0          7             4             8.0        33         0.0   

    Died_bed_days  Hospitalisations  Bed_days_category  
66            0.0                 1                  0  
82            0.0                 1                  0  
83            0.0                 4                  0  
84            0.0                 1                  0  
85            0.0                 8                  1

In [107]:
X5 = filtered_data5[['Count of cases', 'Died_cases', 'Hospitalisations']]
y5 = (filtered_data5['Bed days'] > 30).astype(int) 

In [113]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.2)

xgb_classifier5 = XGBClassifier(random_state=42,scale_pos_weight=2)
xgb_classifier5.fit(X_train5, y_train5)

y_predxgb5 = xgb_classifier5.predict(X_test5)

precision_xgb5 = precision_score(y_test5,y_predxgb5)
recall_xgb5= recall_score(y_test5, y_predxgb5)
f1_xgb5= f1_score(y_test5,y_predxgb5)
print(precision_xgb5)
print(recall_xgb5)
print(f1_xgb5)
print(confusion_matrix(y_true=y_test5,y_pred=y_predxgb5))

0.7516425755584757
0.7677852348993288
0.7596281540504648
[[1861  189]
 [ 173  572]]
