In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC


In [2]:
data = pd.read_csv('final_with_covid_AS.csv')
data.head()

CountCases  BedDys  BeddystoCC  Severity  DiedCases  DiedBdDys  Hsptlsns  \
0          17     133    7.823529        75          4          9        13   
1          13     372   28.615385        63          4         34         9   
2           8     106   13.250000        48          4         13         4   
3          45     218    4.844444       153          3         24        42   
4          24     238    9.916667        90          3          8        21   

   April  August  December  ...  Y2013  Y2014  Y2015  Y2016  Y2017  Y2018  \
0      0       0         0  ...      1      0      0      0      0      0   
1      0       0         0  ...      0      0      0      0      0      0   
2      0       0         0  ...      0      0      0      0      0      1   
3      0       0         0  ...      0      0      0      1      0      0   
4      0       1         0  ...      1      0      0      0      0      0   

   Y2019  Y2020  Y2021  CovidPrd  
0      0      0      0         0  
1      0      0      0         0  
2      0      0      0         0  
3      0      0      0         0  
4      0      0      0         0  

[5 rows x 58 columns]

In [4]:
filtered_data = data[data['CarDriver'] == 1]
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12582 entries, 11 to 54025
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CountCases       12582 non-null  int64  
 1   BedDys           12582 non-null  int64  
 2   BeddystoCC       12582 non-null  float64
 3   Severity         12582 non-null  int64  
 4   DiedCases        12582 non-null  int64  
 5   DiedBdDys        12582 non-null  int64  
 6   Hsptlsns         12582 non-null  int64  
 7   April            12582 non-null  int64  
 8   August           12582 non-null  int64  
 9   December         12582 non-null  int64  
 10  February         12582 non-null  int64  
 11  January          12582 non-null  int64  
 12  July             12582 non-null  int64  
 13  June             12582 non-null  int64  
 14  March            12582 non-null  int64  
 15  May              12582 non-null  int64  
 16  November         12582 non-null  int64  
 17  October    

In [6]:
num_bins = 3

bed_days_min = filtered_data['Severity'].min()
bed_days_max = filtered_data['Severity'].max()

bin_width = (bed_days_max - bed_days_min) / num_bins
bins = [bed_days_min + i * bin_width for i in range(num_bins + 1)]

def bin_function(x):
    for i in range(1, len(bins)):
        if x <= bins[i]:
            return i - 1
    return i

filtered_data['Bed_days_category'] = filtered_data['Severity'].apply(bin_function)

/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1218/3206971614.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Bed_days_category'] = filtered_data['Severity'].apply(bin_function)


In [9]:
print(filtered_data['Bed_days_category'].unique())
print(filtered_data['Bed_days_category'].value_counts())

[2 1 0]
0    11983
1      495
2      104
Name: Bed_days_category, dtype: int64


In [11]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

# تقسیم‌بندی داده‌ها به ورودی و خروجی


# تقسیم داده‌ها به مجموعه‌های آموزش و آزمون
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ایجاد و آموزش مدل XGBoost
model = XGBClassifier(objective='multi:softprob', num_class=3, random_state=42)
model.fit(X_train, y_train)

# ارزیابی مدل
y_pred_xgb = model.predict(X_test)
acc_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)

precision_xgb = precision_score(y_test, y_pred_xgb, average='weighted') 
recall_xgb = recall_score(y_test, y_pred_xgb, average='weighted')
f1_xgb = f1_score(y_test, y_pred_xgb, average='weighted')

print('Accuracy:', acc_xgb)
print('Confusion Matrix:\n', conf_matrix_xgb)
print('Classification Report:\n', class_report_xgb)
print('Precision:', precision_xgb)
print('Recall:', recall_xgb)
print('F1-score:', f1_xgb)

Accuracy: 0.9825188716726262
Confusion Matrix:
 [[2381   13    0]
 [  15   83    7]
 [   0    9    9]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      2394
           1       0.79      0.79      0.79       105
           2       0.56      0.50      0.53        18

    accuracy                           0.98      2517
   macro avg       0.78      0.76      0.77      2517
weighted avg       0.98      0.98      0.98      2517

Precision: 0.9821762101184399
Recall: 0.9825188716726262
F1-score: 0.9823342301454859


In [27]:
from imblearn.combine import SMOTEENN

smoteenn = SMOTEENN(random_state=42)
X_train_resampled, y_train_resampled = smoteenn.fit_resample(X_train, y_train)

model = XGBClassifier(objective='multi:softprob', num_class=3, random_state=42)
model.fit(X_train_resampled, y_train_resampled)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
f1 = f1_score(y_test, y_pred, average='weighted')
print(f1)


              precision    recall  f1-score   support

           0       1.00      0.97      0.99      2394
           1       0.60      0.89      0.72       105
           2       0.48      0.67      0.56        18

    accuracy                           0.97      2517
   macro avg       0.69      0.84      0.75      2517
weighted avg       0.98      0.97      0.97      2517

0.9718992173135605


In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# تقسیم داده‌ها به مجموعه‌های آموزش و آزمون
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# مدل‌های پایه
base_models = [
    LogisticRegression(random_state=42),
    RandomForestClassifier(random_state=42),
    GradientBoostingClassifier(random_state=42)
]

# آموزش مدل‌های پایه
for model in base_models:
    model.fit(X_train, y_train)

# ایجاد ویژگی‌های جدید از خروجی مدل‌های پایه
X_train_meta = [model.predict_proba(X_train) for model in base_models]
X_train_meta = np.concatenate(X_train_meta, axis=1)

X_test_meta = [model.predict_proba(X_test) for model in base_models]
X_test_meta = np.concatenate(X_test_meta, axis=1)

# ایجاد و آموزش مدل متا-طبقه‌بند
meta_model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))
meta_model.fit(X_train_meta, y_train)

# ارزیابی مدل
y_pred = meta_model.predict(X_test_meta)
acc = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print('Accuracy:', acc)
print('Confusion Matrix:\n', conf_matrix)
print('Classification Report:\n', class_report)

Accuracy: 0.9793404847040127
Confusion Matrix:
 [[2383   11    0]
 [  26   74    5]
 [   0   10    8]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      2394
           1       0.78      0.70      0.74       105
           2       0.62      0.44      0.52        18

    accuracy                           0.98      2517
   macro avg       0.79      0.71      0.75      2517
weighted avg       0.98      0.98      0.98      2517



In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# تقسیم داده‌ها به مجموعه‌های آموزش و آزمون
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# مدل‌های پایه
base_models = [
    LogisticRegression(random_state=42),
    RandomForestClassifier(random_state=42),
    GradientBoostingClassifier(random_state=42),
]

# آموزش مدل‌های پایه
for model in base_models:
    model.fit(X_train_resampled, y_train_resampled)

# ایجاد ویژگی‌های جدید از خروجی مدل‌های پایه
X_train_meta = [model.predict_proba(X_train) for model in base_models]
X_train_meta = np.concatenate(X_train_meta, axis=1)

X_test_meta = [model.predict_proba(X_test) for model in base_models]
X_test_meta = np.concatenate(X_test_meta, axis=1)

# ایجاد و آموزش مدل متا-طبقه‌بند
meta_model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))
meta_model.fit(X_train_meta, y_train)

# ارزیابی مدل
y_pred = meta_model.predict(X_test_meta)
acc = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print('Accuracy:', acc)
print('Confusion Matrix:\n', conf_matrix)
print('Classification Report:\n', class_report)

Accuracy: 0.9725864123957092
Confusion Matrix:
 [[2375   16    3]
 [  36   62    7]
 [   2    5   11]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.99      0.99      2394
           1       0.75      0.59      0.66       105
           2       0.52      0.61      0.56        18

    accuracy                           0.97      2517
   macro avg       0.75      0.73      0.74      2517
weighted avg       0.97      0.97      0.97      2517



/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
